# ==================================================================
#  tubex-lib - travis test script
# ==================================================================

language: c++

addons:
  apt:
    sources:
    - deadsnakes
    - ubuntu-toolchain-r-test
    - chef-current-precise

    packages:
    - cmake
    - g++-5
    #- doxygen # for documentation
    #- graphviz # for documentation

sudo: required

matrix:
  include:
  - os: linux
    #language: python
    #env: PYTHON=3.6 CPP_VERSION=11 GCC=5.0
    #compiler: g++-5

install:
  #- sudo pip install breathe # for documentation

  # IBEX
  
  - echo 'Installing IBEX...';
  - git clone https://github.com/SimonRohou/ibex-lib
  - cd ibex-lib
  - git checkout for_tubex_python
  - ./waf configure --with-debug --interval-lib=gaol
  - sudo ./waf install
  - cd ..
  # todo: use CMake to install IBEX

  # IBEX-Geometry:

  #- echo 'Installing IBEX-geometry...';
  #- git clone https://github.com/benEnsta/ibex-geometry
  #- cd ibex-geometry
  #- mkdir make
  #- cd make
  #- cmake -DWITH_PYTHON=OFF -DBUILD_TESTS=OFF -DIBEX_INCLUDE_DIR=/usr/local/include/ibex/ -DFILIB_INCLUDE_DIR=/usr/local/include/ibex/3rd/ -DPC_IBEX_LIBRARY_DIRS=/usr/local/lib/ibex/3rd/ -DCMAKE_CXX_STANDARD=11 ..
  #- sudo make install
  #- cd ..
  #- cd ..

script:
  
  - pwd
  - ls

  # Without synthesis tree
  - export AUTO_SYNTHESIS_BY_DEFAULT=false
  - ./build.sh all clean
  - cd make ; make test
  - cd ..
  
  # With synthesis tree for all created tubes
  - export AUTO_SYNTHESIS_BY_DEFAULT=true
  - ./build.sh all clean
  - cd make ; make test