# ==================================================================
#  tubex-lib - travis test script
# ==================================================================

language: c++

addons:
  apt:
    sources:
      - deadsnakes
      - chef-current-precise
      - ubuntu-toolchain-r-test

    packages:
      - cmake
      - python3.5

matrix:
  include:
  - os: linux
    addons:
      apt:
        packages:
          - g++-5
    env:
      - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"
  - os: linux
    addons:
      apt:
        packages:
          - g++-7
    env:
      - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
  - os: linux
    addons:
      apt:
        packages:
          - g++-8
    env:
      - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"

before_install:
  - eval "${MATRIX_EVAL}"

cache:
  directories:
    - $HOME/capd
    - $HOME/ibex-lib

#services:
#  - docker
#
#env: DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64

install:
  
  # For documentation
  - sudo python3 -m pip install sphinx_rtd_theme breathe sphinx-tabs
  - sudo apt-get install python3-sphinx doxygen graphviz

#  - docker pull $DOCKER_IMAGE
  
  - pwd
  - ls

  # IBEX
  - cd $HOME
  - echo 'Installing IBEX...';
  - if [ ! -e "ibex-lib/README.md" ]; then
      git clone -b develop https://github.com/ibex-team/ibex-lib.git ;
      cd ibex-lib ;
      git checkout 47fc75a5e14eb2f353ae7e0b37ac0f9dad7801c0 ;
      mkdir build && cd build ;
      cmake -DCMAKE_CXX_FLAGS="-fPIC" -DCMAKE_C_FLAGS="-fPIC" -DCMAKE_INSTALL_PREFIX=$HOME/ibex-lib/build_install .. ;
      make ;
      make install ;
    else
      echo 'Using cached directory.' ;
    fi

  # CAPD
  - cd $HOME
  - echo 'Installing CAPD...';
  - if [ ! -e "capd/README.md" ]; then
      svn co https://svn.capdnet.ii.uj.edu.pl/capd/ --non-interactive --trust-server-cert-failures=unknown-ca,cn-mismatch,expired,not-yet-valid,other ;
      cd capd ;
      svn co https://svn.capdnet.ii.uj.edu.pl/capdDynSys4 --non-interactive --trust-server-cert-failures=unknown-ca,cn-mismatch,expired,not-yet-valid,other ;
      autoreconf --install ;
      ./configure --with-filib=check --with-mpfr=check ;
      make ;
    else
      echo 'Using cached directory.' ;
    fi
  - cd $HOME/capd
  - sudo make install
  - cd $HOME

  # Environment variables
  - export CMAKE_PREFIX_PATH=$CMAKE_PREFIX_PATH:$HOME/tubex-lib/build_install
  - export CMAKE_PREFIX_PATH=$CMAKE_PREFIX_PATH:$HOME/ibex-lib/build_install
  - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib

script:

  - py_version=$(python -c "import sys; print(sys.version[:3])") # default python version
  - echo "$py_version"
  
  - cd $HOME/build/SimonRohou/tubex-lib
  - pwd
  - ls
  - git submodule init ; git submodule update # for pybind11 submodule
  - mkdir build -p
  - cd build
  
  # Without synthesis tree
  
  # Building lib + tests
  - cmake -DCMAKE_INSTALL_PREFIX=$HOME/tubex-lib/build_install -DCMAKE_PREFIX_PATH=$HOME/ibex-lib/build_install -DBUILD_TESTS=ON -DWITH_TUBE_TREE=OFF -DWITH_CAPD=ON -DPYTHON_VERSION="$py_version" ..
  - make
  - make api
  - make doc
  - make install
  # Building the examples
  - cd ../examples
  - find . -type d -name build -prune -exec rm -rf {} \;
  - cd basics
  - find . -name "ex\_*" | xargs -L 1 bash -c 'cd "$0" && ./build.sh && cd ..'
  - cd ../robotics
  - find . -name "ex\_*" | xargs -L 1 bash -c 'cd "$0" && ./build.sh && cd ..'
  - cd ../tuto
  - find . -name "ex\_*" | xargs -L 1 bash -c 'cd "$0" && ./build.sh && cd ..'
  - cd ../../build
  # Testing
  - make test
    
  # With synthesis tree for all created tubes
  
  # Building lib + tests
  - cmake -DCMAKE_INSTALL_PREFIX=$HOME/tubex-lib/build_install -DCMAKE_PREFIX_PATH=$HOME/ibex-lib/build_install -DBUILD_TESTS=ON -DWITH_TUBE_TREE=ON -DWITH_CAPD=ON -DPYTHON_VERSION="$py_version" ..
  - make
  - make api
  - make doc
  - make install
  # Building the examples
  - cd ../examples
  - find . -type d -name build -prune -exec rm -rf {} \;
  - cd basics
  - find . -name "ex\_*" | xargs -L 1 bash -c 'cd "$0" && ./build.sh && cd ..'
  - cd ../robotics
  - find . -name "ex\_*" | xargs -L 1 bash -c 'cd "$0" && ./build.sh && cd ..'
  - cd ../tuto
  - find . -name "ex\_*" | xargs -L 1 bash -c 'cd "$0" && ./build.sh && cd ..'
  - cd ../../build
  # Testing
  - make test