# ==================================================================
#  tubex-lib - travis test script
# ==================================================================

language: c++

addons:
  apt:
    sources:
    - deadsnakes
    - chef-current-precise

    packages:
    - cmake
    #- doxygen # for documentation
    #- graphviz # for documentation

matrix:
  include:
  - os: linux
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - g++-5
    env:
       - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"
  - os: linux
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - g++-7
    env:
       - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
  - os: linux
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - g++-8
    env:
       - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"

before_install:
  - eval "${MATRIX_EVAL}"

cache:
  directories:
    - capd
    - ibex-lib

install:
  #- pip install breathe sphinx-tabs # for documentation

  - pwd
  - ls

  # IBEX
  - echo 'Installing IBEX...';
  - if [ ! -e "ibex-lib/README.md" ]; then
      git clone -b develop https://github.com/ibex-team/ibex-lib.git ;
      cd ibex-lib ;
      git checkout fd820d1ed0a85b8a11f54e9ca7ebc8bb4ffa4335 ;
      mkdir build && cd build ;
      cmake -DCMAKE_CXX_FLAGS="-fPIC" -DCMAKE_C_FLAGS="-fPIC" .. ;
      make ;
      cd ../.. ;
    else
      echo 'Using cached directory.' ;
    fi
  - cd ibex-lib/build
  - sudo make install
  - cd ../..
  # todo: use CMake to install IBEX

  # CAPD
  - echo 'Installing CAPD...';
  - if [ ! -e "capd/README.md" ]; then
      svn co https://svn.capdnet.ii.uj.edu.pl/capd/ --non-interactive --trust-server-cert-failures=unknown-ca,cn-mismatch,expired,not-yet-valid,other ;
      cd capd ;
      svn co https://svn.capdnet.ii.uj.edu.pl/capdDynSys4 --non-interactive --trust-server-cert-failures=unknown-ca,cn-mismatch,expired,not-yet-valid,other ;
      autoreconf --install ;
      ./configure --with-filib=check --with-mpfr=check ;
      make ;
      cd .. ;
    else
      echo 'Using cached directory.' ;
    fi
  - cd capd
  - sudo make install
  - cd ..
  - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib

  # IBEX-Geometry:

  #- echo 'Installing IBEX-geometry...';
  #- git clone https://github.com/benEnsta/ibex-geometry
  #- cd ibex-geometry
  #- mkdir make
  #- cd make
  #- cmake -DWITH_PYTHON=OFF -DBUILD_TESTS=OFF -DIBEX_INCLUDE_DIR=/usr/local/include/ibex/ -DFILIB_INCLUDE_DIR=/usr/local/include/ibex/3rd/ -DPC_IBEX_LIBRARY_DIRS=/usr/local/lib/ibex/3rd/ -DCMAKE_CXX_STANDARD=11 ..
  #- make install
  #- cd ..
  #- cd ..

script:

  - py_version=$(python -c "import sys; print(sys.version[:3])") # default python version
  
  - pwd
  - ls
  - git submodule init ; git submodule update # for pybind11 submodule
  - mkdir build -p
  - cd build
  
  # Without synthesis tree
  
  # Building lib + tests
  - cmake -DBUILD_TESTS=ON -DWITH_TUBE_TREE=OFF -DWITH_CAPD=ON -DPYTHON_VERSION=${py_version} ..
  - make
  - sudo make install
  # Building the examples
  - cd ../examples
  - find . -type d -name build -prune -exec rm -rf {} \;
  - cd basics
  - find . -name "ex\_*" | xargs -L 1 bash -c 'cd "$0" && ./build.sh && cd ..'
  - cd ../robotics
  - find . -name "ex\_*" | xargs -L 1 bash -c 'cd "$0" && ./build.sh && cd ..'
  - cd ../../build
  # Testing
  - make test
    
  # With synthesis tree for all created tubes
  
  # Building lib + tests
  - cmake -DBUILD_TESTS=ON -DWITH_TUBE_TREE=ON -DWITH_CAPD=ON -DPYTHON_VERSION=${py_version} ..
  - make
  - sudo make install
  # Building the examples
  - cd ../examples
  - find . -type d -name build -prune -exec rm -rf {} \;
  - cd basics
  - find . -name "ex\_*" | xargs -L 1 bash -c 'cd "$0" && ./build.sh && cd ..'
  - cd ../robotics
  - find . -name "ex\_*" | xargs -L 1 bash -c 'cd "$0" && ./build.sh && cd ..'
  - cd ../../build
  # Testing
  - make test