# ==================================================================
#  tubex-lib - travis test script
# ==================================================================

language: c++

addons:
  apt:
    sources:
    - deadsnakes
    - chef-current-precise

    packages:
    - cmake
    #- doxygen # for documentation
    #- graphviz # for documentation

sudo: required

matrix:
  include:
  - os: linux
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - g++-5
    env:
       - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"
  - os: linux
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - g++-7
    env:
       - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
  - os: linux
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - g++-8
    env:
       - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"


before_install:
  - eval "${MATRIX_EVAL}"

install:
  #- sudo pip install breathe sphinx-tabs # for documentation

  # IBEX
  
  - echo 'Installing IBEX...';
  - git clone https://github.com/SimonRohou/ibex-lib
  - cd ibex-lib
  - git checkout for_tubex_python
  - ./waf configure --with-debug --interval-lib=gaol
  - sudo ./waf install
  - cd ..
  # todo: use CMake to install IBEX

  # IBEX-Geometry:

  #- echo 'Installing IBEX-geometry...';
  #- git clone https://github.com/benEnsta/ibex-geometry
  #- cd ibex-geometry
  #- mkdir make
  #- cd make
  #- cmake -DWITH_PYTHON=OFF -DBUILD_TESTS=OFF -DIBEX_INCLUDE_DIR=/usr/local/include/ibex/ -DFILIB_INCLUDE_DIR=/usr/local/include/ibex/3rd/ -DPC_IBEX_LIBRARY_DIRS=/usr/local/lib/ibex/3rd/ -DCMAKE_CXX_STANDARD=11 ..
  #- sudo make install
  #- cd ..
  #- cd ..

script:
  
  - pwd
  - ls

  # Without synthesis tree
  - export AUTO_SYNTHESIS_BY_DEFAULT=false
  - ./build.sh all clean
  - cd make ; make test
  - cd ..
  
  # With synthesis tree for all created tubes
  - export AUTO_SYNTHESIS_BY_DEFAULT=true
  - ./build.sh all clean
  - cd make ; make test